### PR TITLE
capture more generic error message

### PR DESCRIPTION
**Pull request by FuhuXia**
more on https://github.com/GSA/data.gov/issues/4704

### CODE REVIEW

**Review by btylerburton — APPROVED** [review]

**Comment by btylerburton** [comment]
Mandatory type checking?

**Comment by FuhuXia** [comment]
> Mandatory type checking?

No. Just all possible status code that solr responds during restarting.

**Comment by btylerburton** [comment]
Screenshot 2024-08-30 at 1 54 15 PM

referring to the typecheck test

**Comment by FuhuXia** [comment]
> Screenshot 2024-08-30 at 1 54 15 PM
> referring to the typecheck test

Ok. Not really our concern. CKAN core has it for its master branch but not enforced on 2.10 branches.

**Pull request merged**
